// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DecryptAndServe(arg1, arg2) {
  return window['go']['main']['App']['DecryptAndServe'](arg1, arg2);
}

export function GetDemoManifest() {
  return window['go']['main']['App']['GetDemoManifest']();
}

export function GetManifest(arg1) {
  return window['go']['main']['App']['GetManifest'](arg1);
}

export function IsLicenseValid(arg1) {
  return window['go']['main']['App']['IsLicenseValid'](arg1);
}

export function LoadDemo() {
  return window['go']['main']['App']['LoadDemo']();
}
