// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {player} from '../models';

export function DecryptAndServe(arg1:string,arg2:string):Promise<main.MediaResult>;

export function GetDemoManifest():Promise<player.ManifestInfo>;

export function GetManifest(arg1:string):Promise<player.ManifestInfo>;

export function IsLicenseValid(arg1:string):Promise<boolean>;

export function LoadDemo():Promise<main.MediaResult>;
